Authentication/Authentication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls'))
]

Authentication/index/urls.py
from xml.dom.minidom import Document
from django.urls import path
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns


app_name = 'index'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.login_form, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='logout'),
    path('git_api/', views.git_API, name='git'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Authentication/index/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank = True)

Authentication/index/forms.py
from dataclasses import fields
from django import forms
from . import models
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=(forms.PasswordInput))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')

class UserInfoForm(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ('facebook_id', 'profile_pic')

Authentication/index/views.py
from urllib import response
from django.shortcuts import render
from . import forms
import requests
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from . import models

# Create your views here.
def git_API(request):
    user = False
    if request.method == 'POST':
        username  = request.POST.get('username')
        url  = 'https://api.github.com/users/%s' % username
        response = requests.get(url)
        user = response.json
    
    return render(request, 'index/api.html', context={'user': user})


def profile(request):
    diction = {

    }
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id

        user_info = User.objects.get(pk=user_id)
        user_more_info = models.UserInfo.objects.get(user__pk=user_id)

        diction = {
            'user_info': user_info,
            'user_more_info': user_more_info,
        }

    return render(request, 'index/index.html', context=diction)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        user_info_form = forms.UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            user_info = user_info_form.save(commit=False)
            user_info.user = user

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']
            
            user_info.save()
            registered = True
    else:
        user_form = forms.UserForm()
        user_info_form = forms.UserInfoForm()
    diction = {
        'user_form': user_form,
        'user_info_form': user_info_form,
        'registered': registered,
    }
    return render(request, 'login/register.html', context=diction)

def login_form(request):
    diction = {}
    return render(request, 'login/login.html', context=diction)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index:profile'))
            else:
                return HttpResponse('Your account is not active!')
        else:
            return HttpResponse('Your info is not correct')
    else:
        return HttpResponseRedirect(reverse('index:profile'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index:login'))

Authentication/templates/index/api.html
{% extends 'index/base.html' %}

{% block bodyblock %}
    <h1>Set Your Url</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Enter a link"> <input type="submit" value="Submit Link">
    </form>
    <h2>Your info</h2>
    {% if user %}
            <p>username: {{user.login}}</p>
            <p>Name: {{user.name}}</p>
            <p>Repos: {{user.public_repos}}</p>        
    {% endif %}
{% endblock %}

Authentication/templates/index/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta HTTP-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
      <!-- CSS only -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
      <title>{{title}}</title>
   </head>
   <body>
      <ul>
         <div class="container">
            <li><a class="active" href="{% url 'index:profile'%}">Profile</a></li>
            
            {% if user.is_authenticated %}
            <li><a href="{% url 'index:logout'%}">LogOut</a></li>
            <li><a href="{% url 'index:git'%}">Find Your Git Account</a></li>
            {%else%}
            <li><a href="{% url 'index:register'%}">Register</a></li>
            <li><a href="{% url 'index:login'%}">Login</a></li>
            {% endif %}


         </div>
      </ul>
      <div class="container">
         {% block bodyblock %}
         {% endblock %}
      </div>
   </body>
   <!-- JavaScript Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</html>

Authentication/templates/index/index.html
{% extends 'index/base.html' %}

{% block bodyblock %}
    <h3>Your profile:</h3>
    <hr>
    {% if user.is_authenticated %}
    <img src="/media/{{user_more_info.profile_pic}}" style="border: 2px solid #008cff; width: 200px; border-radius:50%;">
    <h3>{{user_info.first_name}} {{user_info.last_name}}</h3>
    <h6><strong>Username: </strong>{{user_info.username}}</h6>
    <h6><strong>Email: </strong>{{user_info.email}}</h6>
    <h6><strong>Social Link: </strong><a href="{{user_more_info.facebook_id}}">Facebook</a></h6>
    {% else %}
    <h2 class="alert alert-primary"> Please login First!</h2>
    {% endif %}
    
{% endblock %}

Authentication/templates/login/login.html
{% extends '../index/base.html' %}

{% block bodyblock %}
    <h2>Login Form:</h2>
    <hr>
    <form action="{% url 'index:user_login' %}" method="POST" class="control form-control" style="width: 35%;">
        {% csrf_token %}
        <label for="username"></label>
        <input type="text" name="username" placeholder="Enter Username..." class="control form-control"><br>
        <label for="passwoerd"></label>
        <input type="password" name="password" placeholder="Enter Password" class="control form-control"><br>

        <input type="submit" value="Login" class="btn btn-info">
    </form>
{% endblock bodyblock %}

Authentication/templates/login/register.html
{% extends '../index/base.html' %}

{% block bodyblock %}
    <h2>Register User:</h2>
    <hr>
    {% if registered %}
    <h2 class="btn btn-success">Registered Successfully!</h2>
    {% else %}
    <form enctype="multipart/form-data" method="POST" class="control form-control">
        {% csrf_token %}
        {{user_form.as_p}}
        {{user_info_form.as_p}}

        <input type="submit" value="Register" class="btn btn-info">
    {% endif %}
    </form>
{% endblock bodyblock %}